### ISSUE TITLE
How to get scheme including elements under preview?

### ISSUE THREAD

**Issue by RVisionAutomerge** [octokit/graphql-schema#128]

**Comment by gr2m** [comment]
That is a very good question, I've run into that problem my self recently. I'm not sure what the best strategy would be here.

May I ask how you use the repository right now? What are your use cases?

**Comment by miketheman** [comment]
Similar question - I'm developing a tool to interact with the api with items under preview, and am trying to validate my queries before rendering them against the schema, and since the schema doesn't contain the preview elements, they cannot be validated.

**Comment by miketheman** [comment]
It appears that some elements under preview are being added via the bots: https://github.com/octokit/graphql-schema/pull/189

**Comment by gr2m** [comment]
I don't set any preview headers when downloading the GraphQL schema. It's all automated.

Maybe a workable approach could be to set all available preview headers in a 2nd request and store that, too, as something such as `schema-with-previews.{graphql,json}`?

**Comment by gr2m** [comment]
This problem will resolve itself soon, as GitHub is phasing out previews right now

**Comment by rgreenblatt** [comment]
As a solution for right now, you can use apollo (or similar) to inspect the schema with the right `Accept` header.
For instance:
```bash
apollo  client:download-schema --header "Authorization: token $GITHUB_API_TOKEN" --header "Accept: application/vnd.github.hawkgirl-preview+json" --endpoint https://api.github.com/graphql github_schema.graphql
```

**Comment by gr2m** [comment]
There is nothing actionable for us todo here. GitHub's previews are being phased out, and @rgreenblatt provided a workaround
