### ISSUE TITLE
Add Typescript Types

### ISSUE THREAD

**Issue by blimmer** [octokit/graphql-schema#285]
It would be great to have Typescript types along with this package.

**Comment by gr2m** [comment]
I'm not sure how that would work? Could you share a code example of how you wish it would work?

**Comment by blimmer** [comment]
Sure thing - I'm talking about module types for when this package is used. Since the library is written in Javascript, when I import it there are no type signatures for any of the methods.

<img width="929" alt="Screen Shot 2020-05-04 at 6 31 56 PM" src="https://user-images.githubusercontent.com/630449/81025931-a3c18100-8e35-11ea-85c8-1e0c34a0d03b.png">

There are also no types available in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) for this package.

I added the types for the method I'm using (`validate`) like this:

```
// types/graphql-schema.d.ts
declare module "@octokit/graphql-schema" {
  import { GraphQLError } from "graphql";

  export function validate(query: string): ReadonlyArray<GraphQLError>;
}
```

It would be nice if these were provided by the library itself as ambient types, or as a package available in DefinitelyTyped.

**Comment by gr2m** [comment]
Ah I understand now, thank you. Happy to accept a pull request adding a declaration file to make the library working for you.

Somewhat unrelated question: may I ask how you use this library? I'm curious 😁

**Comment by blimmer** [comment]
Hey @gr2m - here's a writeup of how I'm using this repo: https://benlimmer.com/2020/05/16/adding-typescript-types-github-graphql-api/ . Happy to connect if you have any other questions about the use-case.
