### ISSUE TITLE
add `schema.d.ts`?

### ISSUE THREAD

**Issue by JounQin** [octokit/graphql-schema#393]
As title?

**Comment by gr2m** [comment]
sorry I'm not sure what you are asking?

**Comment by JounQin** [comment]
Hmm... I mean can we ship a full `schema.d.ts` generated by `schema.graphql` at the same time?

**Comment by gr2m** [comment]
I guess we could 🤔 What would be a use case for it?

**Comment by gr2m** [comment]
>  I want to import the types in schema manually into ts query expressions.

I didn't know that is possible! Do you have any references where I can read up on it?

Please feel free to start a pull request, make sure to update the README.md file to tell people how to set this up with `gql`.

I wonder if we could set this up to work with https://github.com/octokit/graphql.js, too?

**Comment by JounQin** [comment]
@gr2m Just sent a PR, and it does work with `@octokit/graphql`.

https://github.com/JounQin/graphql-schema/blob/feat/d-ts/README.md#schema-as-types
