### ISSUE TITLE
TypeError: Cannot read property 'Merged' of undefined

### ISSUE THREAD

**Issue by lszomoru** [octokit/graphql-schema#402]
Create a TypeScript file `foo.ts` with the following code:

```
import { PullRequestState } from '@octokit/graphql-schema';

const x: PullRequestState = PullRequestState.Merged;
console.log(x === PullRequestState.Merged);
```

Run `tsc foo.ts` which will generate `foo.js`.
Run `node foo.js` and you will receive the following error:

`TypeError: Cannot read property 'Merged' of undefined`

**Comment by gr2m** [comment]
`PullRequestState` is just a type, not a value. See the usage example in the README. Am I missing something @JounQin?

**Comment by lszomoru** [comment]
`PullRequestState` is a string enum and there are known issues with string enums in `.d.ts` files.
One option would be switch the enum to a union type or to a `const` enum.

**Comment by lszomoru** [comment]
Thank you very much for the quick turnaround!

**Comment by gr2m** [comment]
Mostly thanks to release automation via https://github.com/semantic-release/semantic-releas :)

**Comment by lszomoru** [comment]
🤖 💪🏻
