### ISSUE TITLE
import GraphQLError fails

### ISSUE THREAD

**Issue by webstech** [octokit/graphql-schema#423]
Node project has Typescript compile failing with:
```
node_modules/@octokit/graphql-schema/index.d.ts:1:30 - error TS2307: Cannot find module 'graphql' or its corresponding type declarations.

1 import { GraphQLError } from "graphql";
```
From the npm page for @octokit/graphql-schema, a similar problem occurs when using the runkit option.  Opening the runkit page and trying to run the following gets an error.

```
var graphqlSchema = require("@octokit/graphql-schema")
console.log("hi");
```

graphql is installed as part of core. Missing export somewhere?

**Comment by gr2m** [comment]
Seems to be working as expected now?
https://runkit.com/gr2m/octokit-graphql-schema-423

**Comment by webstech** [comment]
> Seems to be working as expected now?

Yes, the ts compile is now working.  Thanks for the quick response.
