### ISSUE TITLE
The fixedAt property is missing for the type RepositoryVulnerabilityAlert

### ISSUE THREAD

**Issue by Vincent-FundApps** [octokit/graphql-schema#562]
The fixedAt property is missing from the schema for the type RepositoryVulnerabilityAlert

**Comment by wolfy1339** [comment]
Hi @Vincent-FundApps, can you check if this is still an issue with the latest release of the schemas

**Comment by wolfy1339** [comment]
Closing since no response, and the type for `fixedAt` is present in the generated output for `RepositoryVulnerabilityAlert`.
