### ISSUE TITLE
The project next items are not available in the graphql schema

### ISSUE THREAD

**Issue by martin-cycle** [octokit/graphql-schema#565]
The types and resolvers related to the project (beta) are not available yet in the library. Is it planned to add it ?
To give some context, I am currently building an integration with the new github project and I am using octokit as a client but I would have liked to be able to type my entities correctly with the @octokit/graphql-schema library.

**Comment by ngfgrant** [comment]
Agreed, it would be good to have access to these types in some way (maybe via some flag as they are beta). 

I was attempting to codegen the queries and types from oktokit for a simple typescript app and got the following error:

```
Something went wrong GraphQL Document Validation failed with 1 errors;
  Error 0: GraphQLDocumentError: Cannot query field "projectNextItems" on type "Issue".
```

However the query I am attempting is valid via the [Explorer](https://docs.github.com/en/graphql/overview/explorer). The query is detailed below for reference.

```graphql
query MyQuery($org: String!, $repo: String!, $milestone: Int!) {
  organization(login: $org) {
    repository(name: $repo) {
      milestone(number: $milestone) {
        id
        dueOn
        progressPercentage
        url
        title
        issues(first: 100) {
          edges {
            node {
              closedAt
              title
              updatedAt
              url
              assignees(first: 10) {
                nodes {
                  name
                }
              }
              labels(first: 20) {
                nodes {
                  name
                }
              }
              createdAt
              projectNextItems(first: 10) {
                nodes {
                  fieldValues(first: 10) {
                    nodes {
                      value
                      projectField {
                        name
                        settings
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by wolfy1339** [comment]
The schema files in this repository are automatically generated, from GitHub's `/graphql` endpoint. We don't control what is documented.

The types seem to be available in the schema currently, please holler if that isn't the case
