### ISSUE TITLE
[FEAT]: Connection objects should have fewer nullable fields

### ISSUE THREAD

**Issue by jyasskin** [octokit/graphql-schema#983]
### Describe the need

I'm using graphql-codegen to get typescript types for the return values of queries to github, using https://github.com/octokit/graphql-schema/blob/main/schema.graphql as the schema. I've noticed that, for example, in a `repository(...){issues(...) {nodes{...}}}` query, the `result.repository.issues.nodes` field can be null, and if it's not, then elements of that array can be null. The meaning of that result isn't addressed in the [documentation](https://docs.github.com/en/graphql/reference/objects#issueconnection), and I hope it's impossible. If it is impossible, I think https://github.com/octokit/graphql-schema/blob/abea5069314512040ec6c1385cddc118785f59c2/schema.graphql#L18846 should be typed as `nodes: [Issue!]!` rather than the current `nodes: [Issue]`.

Every Connection and Edge type has this issue, and it'd be nice if someone at Github would check if null results are actually possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The schema is downloaded from GitHub directly, we have no control over it's contents

**Comment by jyasskin** [comment]
Whoops, sorry for the noise then. I've opened a discussion at https://github.com/orgs/community/discussions/139032, in the hope that that's the right place for this sort of feedback.

**Comment by wolfy1339** [comment]
That wold indeed be the proper channel for these types of issues.
